blank_issues_enabled: false
contact_links:
  - name: Questions or discussion
    url: https://github.com/michaelcain123/triptrakerdeduct/discussions
    about: Please use Discussions for general questions or ideas.
